### ISSUE TITLE
Warning: XYZ not stored on disc

### ISSUE THREAD

**Issue by tk3369** [julia-vscode/SymbolServer.jl#124]
The linter is underlying every function/type in my package and so I started looking for errors in the log.  From the Julia Language Server window in the Output tab, I found the following:

```
[ Info: Starting the Julia Language Server
┌ Warning: MacroTools not stored on disc
└ @ SymbolServer ~/.vscode-server/extensions/julialang.language-julia-0.15.18/scripts/languageserver/packages/SymbolServer/src/SymbolServer.jl:164
┌ Warning: MacroTools not stored on disc
└ @ SymbolServer ~/.vscode-server/extensions/julialang.language-julia-0.15.18/scripts/languageserver/packages/SymbolServer/src/SymbolServer.jl:164
[ Info: Received new data from Julia Symbol Server.
```

From another project, I found the following:
```
[ Info: Starting the Julia Language Server
┌ Warning: EzXML not stored on disc
│   cache_path = "/home/tkwong/.vscode-server/extensions/julialang.language-julia-0.15.18/scripts/languageserver/packages/SymbolServer/store/Julia-1.4.0-x86_64--normal-0fa3b52a04a4e210aeb1626def9c90df3ae65268.jstore"
└ @ SymbolServer ~/.vscode-server/extensions/julialang.language-julia-0.15.18/scripts/languageserver/packages/SymbolServer/src/SymbolServer.jl:164
[ Info: Received new data from Julia Symbol Server.
```

Note that I monkey-patched the `@warn` statement with `cache_path` so I can see what it's looking for although I don't know how to make sense out of it.

The funny thing is that the linter seems to be problematic for some files but not all of them.  It's like half of the symbols are lost.

My versions:
```
Version: 1.43.2 (user setup)
Commit: 0ba0ca52957102ca3527cf479571617f0de6ed50
Date: 2020-03-24T07:38:38.248Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17134
```

Julia version:
```
julia> versioninfo()
Julia Version 1.4.0
Commit b8e9a9ecc6 (2020-03-21 16:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) Gold 6144 CPU @ 3.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
Environment:
  JULIA_HOME = /home/tkwong/Apps/julia-1.4.0
  JULIA_EDITOR = "/home/tkwong/.vscode-server/bin/0ba0ca52957102ca3527cf479571617f0de6ed50/node"
  JULIA_NUM_THREADS = 1
```

**Comment by tk3369** [comment]
A little more observation:
The packages that appear in the warnings are not direct dependencies.  For example, my package does not use MacroTools directly but it uses PyCall which has MacroTools dependency.  However, not all indirect dependencies generate the same warning....

**Comment by davidanthoff** [comment]
Yeah, there is something weird going on. I'm moving this over to the SymbolServer.jl repo.

**Comment by dpad** [comment]
@davidanthoff Same issue here on 0.15.19. Not sure how helpful this is, but the discrepancy seems to be:

* `load_project_packages_into_store!` calls `load_package_from_cache_into_store!` on the contents of the `Manifest.toml` (in `SymbolServer.jl`)
* The cache store is populated only from `toplevel_pkgs = deps(project(ctx))` (i.e. the `Project.toml` packages) (in `server.jl`).

**Comment by davidanthoff** [comment]
I think @ZacLN might have fixed this bug with the recent (fairly) extensive changes to SymbolServer.jl. Lets see whether this is still a problem once I've pushed out a new release.

**Comment by dpad** [comment]
@davidanthoff Seems to me to be working great as of julia-vscode 0.15.23, thanks for all your work (and @ZacLN)! :)

**Comment by davidanthoff** [comment]
Cool, then I'm going to close this for now.
