### ISSUE TITLE
Pkg changes in Julia 1.4

### ISSUE THREAD

**Issue by ashiklom** [julia-vscode/SymbolServer.jl#125]
Issues with `src/symbols.jl` in Julia 1.4:

- `Pkg.Types.is_stdlib` now only takes one argument -- `uuid`
- `Pkg.API.dir` is deprecated (it should have thrown a [warning since at least Julia 1.3](https://github.com/JuliaLang/Pkg.jl/blob/5de608c7b1837a24ed84eaaa14dde017986cb460/src/API.jl#L673))

EDIT: I _think_ the following patch resolves this issue:

```
modified   src/symbols.jl
@@ -207,13 +207,20 @@ function cache_package(c::Pkg.Types.Context, uuid::UUID, depot::Dict, env_path =
         end
     end
 
+    pkgpath = try
+        LoadingBay.eval(:(import $(Symbol(pe_name))))
+        LoadingBay.eval(:(joinpath(dirname(pathof($(Symbol(pe_name)))), "..")))
+    catch err
+        return nothing
+    end
+
     # Dependencies
     for pkg in deps(pe)
         if path(pe) isa String
             env_path = path(pe)
             Pkg.API.activate(env_path)
-        elseif !is_stdlib(uuid) && ((Pkg.API.dir(pe_name) isa String) && !isempty(Pkg.API.dir(pe_name)))
-            env_path = Pkg.API.dir(pe_name)
+        elseif !is_stdlib(uuid) && (pkgpath isa String) && !isempty(pkgpath)
+            env_path = pkgpath
             Pkg.API.activate(env_path)
         end
         cache_package(c, packageuuid(pkg), depot, env_path)
```

**Comment by non-Jedi** [comment]
SymbolServer.jl doesn't use is_stdlib any longer. To my eyes, it looks like the last usage of `is_stdlib` was removed in eacbc79a2ed1c646f642c579de3c5c0653edc71e. This error shouldn't occur if lsp-julia uses an up-to-date version.

**Comment by davidanthoff** [comment]
Ah, good point! So I'm going to close this for now, assuming that this was just based on out-dated package versions.

I did a round of tagging of packages today, so you should be able to get the latest combo of all packages easily.
