### ISSUE TITLE
Incorrect deprecation warnings

### ISSUE THREAD

**Issue by aminya** [julia-vscode/SymbolServer.jl#173]
When I run the following code, I get a lot of deprecation warnings which seem to be incorrect:
```julia
using SymbolServer
env = SymbolServer.getenvtree()
```

```julia
WARNING: Compat.Random is deprecated, use Random instead.

WARNING: Compat.LibGit2 is deprecated, use LibGit2 instead.

...
```

**Comment by pfitzseb** [comment]
[Those bindings *are* deprecated](https://github.com/JuliaLang/Compat.jl/blob/master/src/deprecated.jl#L18-L26), and the deprecation warning is thrown when they are resolved. I don't think there's a way around this.

**Comment by aminya** [comment]
Hmm. I did not know that Compat exports that many symbols! It seemed strange to me.
