### ISSUE TITLE
Small change in Pkg internals in 1.6.2.

### ISSUE THREAD

**Issue by KristofferC** [julia-vscode/SymbolServer.jl#224]
To handle the upcoming new 1.7 manifest format in 1.6, a backport was made to Pkg that slightly changed the internals.
This caused the tests here to error. The error can be seen in https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/6d74a23_vs_dd12291/SymbolServer.1.6.2-pre-257e784638.log.

It should be quite easy to workaround.

**Comment by pfitzseb** [comment]
Thanks for the headsup!

**Comment by fredrikekre** [comment]
1.6.2 is out now so would be great to have a fix for this.
