### ISSUE TITLE
Cannot start coc-julia using 1.6.2

### ISSUE THREAD

**Issue by tpoisot** [julia-vscode/SymbolServer.jl#231]
As of a few days ago, `coc-julia` was unable to detect packages correctly - see the issue I opened here: https://github.com/fannheyward/coc-julia/issues/234

The crux of the issue is that there seems to be a missing method I'm `SymbolServer`, as this is the LSP error:

~~~
[Trace - 11:24:11 AM] Received notification 'telemetry/event'.
Params: {
    name: LSSymbolServerFailure,
    stacktrace: "",
    message: "
        ERROR: LoadError: MethodError: no method matching frommanifest(::Pkg.Types.Manifest, ::Base.UUID)
        Closest candidates are:
            frommanifest(!Matched::Pkg.Types.Context, ::Any) at ~/.julia/packages/SymbolServer/mibRY/src/utils.jl:128
            frommanifest(!Matched::Dict{Base.UUID, Pkg.Types.PackageEntry}, ::Any) at ~/.julia/packages/SymbolServer/mibRY/src/utils.jl:129
        Stacktrace:
        [1] top-level scope
            @ ~/.julia/packages/SymbolServer/mibRY/src/server.jl:61
            in expression starting at ~/.julia/packages/SymbolServer/mibRY/src/server.jl:1
    ",
    "command": "symserv_crash"
}
~~~

I have removed the `Manifest.toml` files that came with `coc-julia` , and tried with the master version of every package, but the error remains.

**Comment by pfitzseb** [comment]
That bug got fixed in https://github.com/julia-vscode/SymbolServer.jl/pull/229, so just use master until we release a new version.

**Comment by davidanthoff** [comment]
I take it this is fixed and we can close? If not, please reopen.
