### ISSUE TITLE
Indexing during pre-compilation

### ISSUE THREAD

**Issue by gzagatti** [julia-vscode/SymbolServer.jl#234]
I am wondering if it's possible to index packages during the pre-compilation stage. 

I am not sure if Julia provides a hook to execute after pre-compilation, but I think it would be a good place to get everything indexed after package management operations.

**Comment by davidanthoff** [comment]
Our current plan is to get rid of indexing entirely on local machines and instead do it in the cloud. That should actually partially ship tomorrow :)
