### ISSUE TITLE
Don't cache by UUID

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/SymbolServer.jl#73]
To work properly with environments, we need to store a distinct cache for different versions of the same package. I would suggest that we use `git-tree-sha1` instead, that should be unique for each package version.

Not sure what to do about deved packages in an env. We can't get the `git-tree-sha1` from the manifest, I think, so maybe we have to just compute it ourselves from the folder on disc? Or maybe we don't cache deved packages at all? In general we'll have to be clever about those, we probably should also add file system watcher on these folders to detect updates in them that trigger a new symbol extraction run. But I'd say we can do that later.

I would also suggest that we include the Julia version and arch in the cached file name, so that folks that switch between different Julia versions get separated caches.

**Comment by ZacLN** [comment]
Yep, we already store it inside the cache (where possible): https://github.com/julia-vscode/SymbolServer.jl/blob/master/src/utils.jl#L167-L185

**Comment by davidanthoff** [comment]
Ah cool.

I guess one other question is what exactly we want to store for deved packages... I think for "normal" packages it makes sense to save a cache file for different versions, but for deved packages we kind of don't need to keep old versions around... Maybe we need one cache file per folder location, and then make sure we detect when it is out-of-date...

So the filename for the cache file could be some hash of the full path to the deved package, and then  we make sure to store that SHA inside the cache file to be able to detect when it is out-of-date.

**Comment by ZacLN** [comment]
My `parallel` branch did a pretty good job of re-caching packages when their sha changed - https://github.com/julia-vscode/SymbolServer.jl/blob/parallel/src/SymbolServer.jl#L50

**Comment by davidanthoff** [comment]
For normal packages we want to be able to keep different versions around. I regularly use multiple versions of the same package in different environments, and that shouldn't trigger a re-caching every time.

But for deved folders that seems pointless, given that one actually can only use the version that is in the folder right now. Yes, I think your re-caching logic in the `parallel` branch is what we should use for deved packages, but not for normal packages.

**Comment by ZacLN** [comment]
agreed
