### ISSUE TITLE
Handle a crash situation

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/SymbolServer.jl#84]
Details [here](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22Name%22%3A%22julia-vscode-dev%22%2C%22SubscriptionId%22%3A%226803c4ed-bcb4-41d4-bceb-7faf5e7a3469%22%2C%22ResourceGroup%22%3A%22Default%22%7D/DataModel/%7B%22eventId%22%3A%22ce2cd9f1-4397-11ea-a465-bf65f500aa6a%22%2C%22timestamp%22%3A%222020-01-30T19%3A35%3A52.870Z%22%2C%22cacheId%22%3A%223c432666-50d3-4941-8700-1f42638ccf7d%22%2C%22eventTable%22%3A%22exceptions%22%7D).

**Comment by ZacLN** [comment]
The details of that crash don't look like something we'd be able to account for so: https://github.com/julia-vscode/SymbolServer.jl/pull/92
